TypeError('list indices must be integers or slices, not str')
ValueError('too many values to unpack (expected 2)')
ValueError('too many values to unpack (expected 2)')
Error: SyntaxError('syntax error at or near "status"\nLINE 3:         SET status=\'Rejected\',\n                    ^\n')
Exception on /api/addrequests [POST]
Traceback (most recent call last):
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1615, in async_to_sync
    from asgiref.sync import async_to_sync as asgiref_async_to_sync
ModuleNotFoundError: No module named 'asgiref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1596, in ensure_sync
    return self.async_to_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1617, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
Exception on /api/addrequests [POST]
Traceback (most recent call last):
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1615, in async_to_sync
    from asgiref.sync import async_to_sync as asgiref_async_to_sync
ModuleNotFoundError: No module named 'asgiref'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1596, in ensure_sync
    return self.async_to_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HCH165\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1617, in async_to_sync
    raise RuntimeError(
RuntimeError: Install Flask with the 'async' extra in order to use async views.
Error: NotNullViolation('null value in column "id" of relation "entries" violates not-null constraint\nDETAIL:  Failing row contains (Add 4G VPN Profile, 1234, , Pending, uuid_testuuid1234, 12/08/2024, CORP, , user_AdminAdmin, , , , 14:48:29, null, ).\n')
Error: ValueError("invalid literal for int() with base 10: ''")
Error: ValueError("invalid literal for int() with base 10: ''")
